/*                                             
 *Copyright 2007, 2011 CCLS Columbia University (USA), LIFO University of Orl��ans (France), BRGM (France)
 *
 *Authors: Cyril Nortet, Xiangrong Kong, Ansaf Salleb-Aouissi, Christel Vrain, Daniel Cassard
 *
 *This file is part of QuantMiner.
 *
 *QuantMiner is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
 *
 *QuantMiner is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 *You should have received a copy of the GNU General Public License along with QuantMiner.  If not, see <http://www.gnu.org/licenses/>.
 */
package src.graphicalInterface;

import java.awt.Font;

import src.tools.*;




public class DialogAbout extends javax.swing.JDialog {  //About Dialog
    
    /*default serial*/
	private static final long serialVersionUID = 1L;
	/** Creates new form DialogAPropos */
    public DialogAbout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        String sTexteAPropos = null;
        String sTexteAProposTitle = null;
        String sTexteAProposSubTitle =null;
        initComponents();

        sTexteAProposTitle = "QuantMiner version "+ENV.VERSION_QUANTMINER;
        sTexteAProposSubTitle = "Distributed under GPL License, Version 3";
        sTexteAPropos = 
        				"\n\nStudents:	Cyril Nortet and Xiangrong Kong" +
        				"\nAdvisors:	Ansaf Salleb-Aouissi (CCLS, Columbia University)\n" +
        				"	Christel Vrain (LIFO, University of Orleans)\n" +
        				"	Daniel Cassard (BRGM, France)";
        
        jTextAreaAPropos.setText(sTexteAPropos);
        jTextAreaAProposTitle.setText(sTexteAProposTitle);
        jTextAreaAProposSubTitle.setText(sTexteAProposSubTitle);
        
        jLabelLogoCCLS.setIcon(new javax.swing.ImageIcon( ENV.REPERTOIRE_RESSOURCES + "logoCCLS.jpg" ));
        jLabelLogoLIFO.setIcon(new javax.swing.ImageIcon( ENV.REPERTOIRE_RESSOURCES + "logoLIFO.png" ));
        jLabelLogoBRGM.setIcon(new javax.swing.ImageIcon( ENV.REPERTOIRE_RESSOURCES + "logoBRGM.jpg" ));
        setLocationRelativeTo(null);    
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanelGeneral = new javax.swing.JPanel();
        jTextAreaAPropos = new javax.swing.JTextArea();
        jTextAreaAProposTitle = new javax.swing.JTextArea();
        jTextAreaAProposSubTitle = new javax.swing.JTextArea();
        jLabelLogoCCLS = new javax.swing.JLabel();
        jLabelLogoLIFO = new javax.swing.JLabel();
        jLabelLogoBRGM = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About QuantMiner");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanelGeneral.setLayout(null);

        jPanelGeneral.setBackground(new java.awt.Color(255, 255, 255));
        jPanelGeneral.setPreferredSize(new java.awt.Dimension(500, 320));
        
        jTextAreaAPropos.setEditable(false);
        jTextAreaAPropos.setFont(new java.awt.Font("Dialog", Font.PLAIN, 12));
        jTextAreaAPropos.setBounds(60, 150, 460, 100);
        jPanelGeneral.add(jTextAreaAPropos); 
        
        jTextAreaAProposTitle.setEditable(false);
        jTextAreaAProposTitle.setFont(new java.awt.Font("Dialog", Font.BOLD, 16));
        jTextAreaAProposTitle.setBounds(150, 15, 200, 25);
        jPanelGeneral.add(jTextAreaAProposTitle);
        
        
        jTextAreaAProposSubTitle.setEditable(false);
        jTextAreaAProposSubTitle.setFont(new java.awt.Font("Dialog", Font.PLAIN, 11));
        jTextAreaAProposSubTitle.setBounds(140, 45, 250, 25);
        jPanelGeneral.add(jTextAreaAProposSubTitle); 
        
        
        jLabelLogoCCLS.setBackground(new java.awt.Color(255, 255, 255));
        jPanelGeneral.add(jLabelLogoCCLS);
        jLabelLogoCCLS.setBounds(30, 60, 180, 100);
        
        jLabelLogoLIFO.setBackground(new java.awt.Color(255, 255, 255));
        jPanelGeneral.add(jLabelLogoLIFO);
        jLabelLogoLIFO.setBounds(220, 60, 100, 100);
        
        jLabelLogoBRGM.setBackground(new java.awt.Color(255, 255, 255));
        jPanelGeneral.add(jLabelLogoBRGM);
        jLabelLogoBRGM.setBounds(350, 60, 100, 100);
  

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jPanelGeneral.add(jButtonOK);
        jButtonOK.setBounds(190, 270, 100, 23);

        getContentPane().add(jPanelGeneral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("deprecation")
	public static void main(String args[]) {
        new DialogAbout(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabelLogoCCLS;
    private javax.swing.JLabel jLabelLogoLIFO;
    private javax.swing.JLabel jLabelLogoBRGM;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JTextArea jTextAreaAProposTitle;
    private javax.swing.JTextArea jTextAreaAProposSubTitle;
    private javax.swing.JTextArea jTextAreaAPropos;
    // End of variables declaration//GEN-END:variables
    
}
